class vsftpd::params {
	$anonymous_enable = "NO"
	$local_enable = "YES"
	$write_enable = "YES"
	$local_umask = "027"
	$anon_upload_enable = "NO"
	$anon_mkdir_write_enable = "NO"
	$dirmessage_enable = "NO"
	$xferlog_enable = "YES"
	$connect_from_port_20 = "YES"
	$xferlog_std_format = "YES"
	$ftpd_banner = "Servico FTP."
	$chroot_local_user = "YES"
	$chroot_list_enable = "YES"
	$chroot_list_file = "/etc/vsftpd/chroot_list"
	$listen = "YES"
	$pam_service_name = "vsftpd"
	$userlist_enable = "YES"
	$tcp_wrappers = "YES"
}